# MAIN DIRECTORY
# --------------
DIR_LOCATION = '/home/andrea/Projects/HippoModel/LCNhippomodel'
OPT_FOLDER_NAME = 'simulation_IOintrinsics_all'

# SIMULATION PROPERTIES
# ---------------------
SIMPROP_THETA_MODE = False
SIMPROP_THETA_PERIOD = 0.
SIMPROP_START_TIME = 0.
SIMPROP_SIM_TIME = 2700
SIMPROP_END_TIME = SIMPROP_START_TIME + SIMPROP_SIM_TIME
SIMPROP_DT = 0.025
SIMPROP_TEMPERATURE = 34.

# CELL CHARACTERISTICS
# --------------------
CELLPROP_MORPHOLOGY = ''
CELLPROP_INDIVIDUAL = 21
CELLPROP_INTRINSIC_IONCHS = ['iNas','iA','iAHPs','iC','iCaL','iCaT','iKDR','iM','iHCN','iL']
CELLPROP_INTRINSIC_EXPERIMENT = [ 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1. ]
CELLPROP_SYNAPTIC_INPUTS = []
CELLPROP_SYNAPTIC_EXPERIMENT = []

# CURRENT OPTIONS
# ---------------
CURRENT_DURATION = [333, 333, 333]
CURRENT_DELAY = [167, 667, 1167]
CURRENT_AMPLITUDES = [0.1, 0.2, 0.3]
CURRENT_SECTION = ['SomaList0', 'SomaList0', 'SomaList0']
CURRENT_LOCATION = [0., 0., 0.]

# RECORDING OPTIONS
# -----------------
RECORDING_MAGNITUDE = ['Vmem']
RECORDING_SECTION = ['SomaList0']
RECORDING_LOCATION = [0.0]
